third deliverable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,7 @@ jobs:
     
     - name: Install Rust target for wasm
       run: |
-        rustup target add wasm32-wasi
+        rustup target add wasm32-wasip1
         
     - name: Install WasmEdge
       run: |
@@ -51,11 +51,19 @@ jobs:
           echo -e "Execution Fail!"
           exit 1
         fi
-        resp=$(curl http://localhost:8001/find_rate -X POST -d "12345")
+        resp=$(curl http://localhost:8001/find_rate -X POST -d "89182")
         echo "$resp"
-        if [[ $resp == "0.08" ]]; then
+        if [[ $resp == "0.0875" ]]; then
           echo -e "Execution Success!"
         else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        resp=$(curl http://localhost:8001/find_rate -X POST -d "00000")
+        echo "$resp"
+        if [[ $resp == "" ]]; then 
+          echo -e "Execution Success!"
+        else 
           echo -e "Execution Fail!"
           exit 1
         fi
